project:
  type: website
  preview:
    port: 4200
  render:
  - '*.qmd'
  - '!misc/'
  resources:
  - slides_data_viz_summer.html
  - slides_data_viz_summer.pdf
  output-dir: docs
execute:
  freeze: auto
website:
  title: Data Viz
  favicon: images/favicon.ico
  site-url: https://vincentbagilet.github.io/data_viz_summer/
  repo-url: https://github.com/vincentbagilet/data_viz_summer/
  navbar:
    left:
    - text: Syllabus
      href: content/syllabus.qmd
    - text: Outline and Resources
      href: content/lect_pages/lect_page_data_viz_summer.qmd
    - text: Slides
      menu:
      - text: PDF
        href: content/slides/slides_data_viz_summer.pdf
      - text: HTML
        href: docs/content/slides/slides_data_viz_summer.html
  page-footer:
    right: |
      Made with R and [Quarto](https://quarto.org/)<br>
      [Source code on GitHub](https://github.com/vincentbagilet/data_viz_summer)
format:
  html:
    toc: true
    theme: vb.scss
    css: include/webex.css
    include-after-body: include/webex.js
