---
title: "Design Beyond Identification"
subtitle: "Design is crutial to ensure causality. Here we discuss to what extent it also matters beyond identification."
published-title: "Date"
date: "2024-10-09"
self-contained: true
engine: knitr
---

::: callout-tip
## Objective

This session aims to underline the importance of design, beyond identification, and how it is affected by the fact that empirical studies often pursue multiple goals.
:::

## Summary

Causal inference studies generally have multiple goals, aiming not only to estimate ``the'' average treatment effect but also analyze how it **varies across individuals and time, how it impacts multiple outcomes, or how these effects can be extrapolated to other populations**. Expecting to produce these multiple estimates, combined with the importance of external validity, can orient choices at the design stage, to ensure the study is set up for success.

To address this, one can make substantively-motivated assumptions about effect sizes and variation in light of the goals of a study, anticipating and allowing for both uncertainty and heterogeneity in effect sizes. 

### Session Outline

1. Projects
1. Design Matters
1. Multiple Goals
1. Improving and Assessing Design

## Materials

`r fontawesome::fa("file-powerpoint")` [Open slides](../../slides/lecture_5/slides_5_design.html)

```{r out.width='100%'}
#| echo: false

knitr::include_url("../../slides/lecture_5/slides_5_design.html")
```

Part of the slides are derived from [notes](https://clairepalandri.github.io/misc/) by [Claire Palandri](https://clairepalandri.github.io/).

<!-- ## Exercise -->

<!-- Before class next week (October 2nd), please send me via email a `html` document, generated with Quarto, implementing the analysis required and answering the questions listed in this [document](exercises/exercise_01_heterogeneity.qmd). -->


## Specific resources for this lecture

- [Aronow and Samii (2016)](https://onlinelibrary.wiley.com/doi/abs/10.1111/ajps.12185) interpret OLS regression as a weighted average of observations, depending on how well the endogenous variable of interest is correlated with other covariates
- [de Chaisemartin and D'Haultfoeuille (2023)](https://academic.oup.com/ectj/article-abstract/26/3/C1/6604378) summarizes the fast-growing literature on TWFE
-   Huntington-Klein, [*The Effect: An Introduction to Research Design and Causality*](https://theeffectbook.net/index.html): an excellent causal inference textbook centered on intuitions and not maths.
-   Cunningham, [*Causal Inference, The Mixtape*](https://mixtape.scunning.com/): a nice overview of causal inference approaches, with R, Python and Stata code and examples
-   Angrist, Joshua D. and Jorn-Stefen Prischke, [*Mostly Harmless Econometrics: An Empiricist’s Companion*](https://press.princeton.edu/books/paperback/9780691120355/mostly-harmless-econometrics?srsltid=AfmBOorXVR0HQg6J2HOtaCQu2sGRsQ1eqAxktoSYKXxshheduu_wROok): the causal inference bible for economists


